! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Auxiliary Routines File
!
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! File                 : gckpp_Util.f90
! Time                 : Thu Feb 11 15:52:32 2021
! Working directory    : /mnt/lustre/users/ts551/GC/Code/Code.BleedingEdge.NOHAL.II/KPP/Tropchem
! Equation file        : gckpp.kpp
! Output root filename : gckpp
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Util

  USE gckpp_Parameters
  IMPLICIT NONE

CONTAINS



! User INLINED Utility Functions

! End INLINED Utility Functions

! Utility Functions from KPP_HOME/util/util
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! UTIL - Utility functions
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! ****************************************************************
!
! InitSaveData - Opens the data file for writing
!   Parameters :
!
! ****************************************************************

      SUBROUTINE InitSaveData ()

      USE gckpp_Parameters

      open(10, file='gckpp.dat')

      END SUBROUTINE InitSaveData

! End of InitSaveData function
! ****************************************************************

! ****************************************************************
!
! SaveData - Write LOOKAT species in the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE SaveData ()

      USE gckpp_Global
      USE gckpp_Monitor

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,  &
                   (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
999   FORMAT(E24.16,100(1X,E24.16))

      END SUBROUTINE SaveData

! End of SaveData function
! ****************************************************************

! ****************************************************************
!
! CloseSaveData - Close the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE CloseSaveData ()

      USE gckpp_Parameters

      CLOSE(10)

      END SUBROUTINE CloseSaveData

! End of CloseSaveData function
! ****************************************************************

! ****************************************************************
!
! GenerateMatlab - Generates MATLAB file to load the data file
!   Parameters :
!                It will have a character string to prefix each
!                species name with.
!
! ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      USE gckpp_Parameters
      USE gckpp_Global
      USE gckpp_Monitor


      CHARACTER(LEN=8) PREFIX
      INTEGER i

      open(20, file='gckpp.m')
      write(20,*) 'load gckpp.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = gckpp;')
      write(20,*) 'clear gckpp;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SPC_NAMES(LOOKAT(i)), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do

      CLOSE(20)

      END SUBROUTINE GenerateMatlab

! End of GenerateMatlab function
! ****************************************************************


! End Utility Functions from KPP_HOME/util/util
! End of UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(155) = V_USER(1)
  V(130) = V_USER(2)
  V(111) = V_USER(3)
  V(12) = V_USER(4)
  V(182) = V_USER(5)
  V(64) = V_USER(6)
  V(199) = V_USER(7)
  V(146) = V_USER(8)
  V(167) = V_USER(9)
  V(52) = V_USER(10)
  V(13) = V_USER(11)
  V(14) = V_USER(13)
  V(1) = V_USER(14)
  V(2) = V_USER(15)
  V(15) = V_USER(16)
  V(59) = V_USER(17)
  V(50) = V_USER(19)
  V(62) = V_USER(20)
  V(54) = V_USER(21)
  V(107) = V_USER(22)
  V(108) = V_USER(23)
  V(189) = V_USER(29)
  V(161) = V_USER(30)
  V(156) = V_USER(32)
  V(16) = V_USER(37)
  V(3) = V_USER(39)
  V(51) = V_USER(40)
  V(4) = V_USER(41)
  V(17) = V_USER(42)
  V(18) = V_USER(43)
  V(202) = V_USER(44)
  V(19) = V_USER(45)
  V(76) = V_USER(46)
  V(77) = V_USER(47)
  V(165) = V_USER(48)
  V(78) = V_USER(49)
  V(137) = V_USER(50)
  V(85) = V_USER(51)
  V(157) = V_USER(52)
  V(185) = V_USER(53)
  V(88) = V_USER(54)
  V(195) = V_USER(55)
  V(147) = V_USER(57)
  V(99) = V_USER(59)
  V(63) = V_USER(61)
  V(79) = V_USER(62)
  V(80) = V_USER(63)
  V(170) = V_USER(64)
  V(81) = V_USER(65)
  V(208) = V_USER(66)
  V(20) = V_USER(67)
  V(21) = V_USER(68)
  V(5) = V_USER(69)
  V(103) = V_USER(70)
  V(144) = V_USER(71)
  V(93) = V_USER(72)
  V(145) = V_USER(73)
  V(90) = V_USER(74)
  V(94) = V_USER(75)
  V(97) = V_USER(76)
  V(132) = V_USER(77)
  V(6) = V_USER(80)
  V(7) = V_USER(81)
  V(8) = V_USER(82)
  V(133) = V_USER(84)
  V(151) = V_USER(85)
  V(193) = V_USER(87)
  V(115) = V_USER(88)
  V(158) = V_USER(89)
  V(84) = V_USER(90)
  V(96) = V_USER(91)
  V(106) = V_USER(92)
  V(191) = V_USER(93)
  V(128) = V_USER(94)
  V(127) = V_USER(95)
  V(124) = V_USER(96)
  V(200) = V_USER(97)
  V(110) = V_USER(98)
  V(101) = V_USER(99)
  V(186) = V_USER(100)
  V(102) = V_USER(101)
  V(187) = V_USER(102)
  V(92) = V_USER(103)
  V(177) = V_USER(104)
  V(105) = V_USER(105)
  V(109) = V_USER(106)
  V(169) = V_USER(107)
  V(196) = V_USER(108)
  V(197) = V_USER(109)
  V(171) = V_USER(110)
  V(149) = V_USER(111)
  V(140) = V_USER(112)
  V(139) = V_USER(113)
  V(141) = V_USER(114)
  V(98) = V_USER(115)
  V(22) = V_USER(116)
  V(204) = V_USER(118)
  V(203) = V_USER(119)
  V(138) = V_USER(120)
  V(117) = V_USER(121)
  V(23) = V_USER(122)
  V(82) = V_USER(123)
  V(9) = V_USER(124)
  V(10) = V_USER(125)
  V(67) = V_USER(126)
  V(24) = V_USER(127)
  V(25) = V_USER(128)
  V(159) = V_USER(129)
  V(126) = V_USER(130)
  V(121) = V_USER(131)
  V(178) = V_USER(132)
  V(194) = V_USER(133)
  V(180) = V_USER(134)
  V(26) = V_USER(135)
  V(27) = V_USER(136)
  V(123) = V_USER(137)
  V(174) = V_USER(138)
  V(28) = V_USER(139)
  V(29) = V_USER(140)
  V(30) = V_USER(141)
  V(31) = V_USER(142)
  V(33) = V_USER(143)
  V(32) = V_USER(144)
  V(34) = V_USER(145)
  V(35) = V_USER(146)
  V(201) = V_USER(147)
  V(160) = V_USER(148)
  V(104) = V_USER(149)
  V(205) = V_USER(150)
  V(65) = V_USER(151)
  V(209) = V_USER(152)
  V(100) = V_USER(153)
  V(114) = V_USER(154)
  V(153) = V_USER(155)
  V(134) = V_USER(156)
  V(188) = V_USER(157)
  V(166) = V_USER(158)
  V(179) = V_USER(159)
  V(68) = V_USER(160)
  V(192) = V_USER(161)
  V(210) = V_USER(162)
  V(135) = V_USER(163)
  V(53) = V_USER(164)
  V(136) = V_USER(165)
  V(152) = V_USER(166)
  V(69) = V_USER(167)
  V(116) = V_USER(168)
  V(66) = V_USER(169)
  V(36) = V_USER(170)
  V(112) = V_USER(171)
  V(113) = V_USER(172)
  V(198) = V_USER(173)
  V(89) = V_USER(174)
  V(129) = V_USER(175)
  V(143) = V_USER(176)
  V(162) = V_USER(177)
  V(190) = V_USER(178)
  V(163) = V_USER(179)
  V(118) = V_USER(180)
  V(57) = V_USER(181)
  V(48) = V_USER(182)
  V(49) = V_USER(183)
  V(211) = V_USER(184)
  V(212) = V_USER(185)
  V(207) = V_USER(186)
  V(70) = V_USER(187)
  V(206) = V_USER(189)
  V(11) = V_USER(190)
  V(213) = V_USER(191)
  V(37) = V_USER(192)
  V(172) = V_USER(193)
  V(173) = V_USER(194)
  V(164) = V_USER(195)
  V(60) = V_USER(196)
  V(175) = V_USER(197)
  V(91) = V_USER(198)
  V(142) = V_USER(199)
  V(86) = V_USER(200)
  V(55) = V_USER(201)
  V(150) = V_USER(202)
  V(154) = V_USER(203)
  V(184) = V_USER(204)
  V(87) = V_USER(205)
  V(83) = V_USER(206)
  V(148) = V_USER(207)
  V(168) = V_USER(208)
  V(176) = V_USER(209)
  V(71) = V_USER(210)
  V(72) = V_USER(211)
  V(73) = V_USER(212)
  V(181) = V_USER(213)

END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(1) = V(155)
  V_USER(2) = V(130)
  V_USER(3) = V(111)
  V_USER(4) = V(12)
  V_USER(5) = V(182)
  V_USER(6) = V(64)
  V_USER(7) = V(199)
  V_USER(8) = V(146)
  V_USER(9) = V(167)
  V_USER(10) = V(52)
  V_USER(11) = V(13)
  V_USER(13) = V(14)
  V_USER(14) = V(1)
  V_USER(15) = V(2)
  V_USER(16) = V(15)
  V_USER(17) = V(59)
  V_USER(19) = V(50)
  V_USER(20) = V(62)
  V_USER(21) = V(54)
  V_USER(22) = V(107)
  V_USER(23) = V(108)
  V_USER(29) = V(189)
  V_USER(30) = V(161)
  V_USER(32) = V(156)
  V_USER(37) = V(16)
  V_USER(39) = V(3)
  V_USER(40) = V(51)
  V_USER(41) = V(4)
  V_USER(42) = V(17)
  V_USER(43) = V(18)
  V_USER(44) = V(202)
  V_USER(45) = V(19)
  V_USER(46) = V(76)
  V_USER(47) = V(77)
  V_USER(48) = V(165)
  V_USER(49) = V(78)
  V_USER(50) = V(137)
  V_USER(51) = V(85)
  V_USER(52) = V(157)
  V_USER(53) = V(185)
  V_USER(54) = V(88)
  V_USER(55) = V(195)
  V_USER(57) = V(147)
  V_USER(59) = V(99)
  V_USER(61) = V(63)
  V_USER(62) = V(79)
  V_USER(63) = V(80)
  V_USER(64) = V(170)
  V_USER(65) = V(81)
  V_USER(66) = V(208)
  V_USER(67) = V(20)
  V_USER(68) = V(21)
  V_USER(69) = V(5)
  V_USER(70) = V(103)
  V_USER(71) = V(144)
  V_USER(72) = V(93)
  V_USER(73) = V(145)
  V_USER(74) = V(90)
  V_USER(75) = V(94)
  V_USER(76) = V(97)
  V_USER(77) = V(132)
  V_USER(80) = V(6)
  V_USER(81) = V(7)
  V_USER(82) = V(8)
  V_USER(84) = V(133)
  V_USER(85) = V(151)
  V_USER(87) = V(193)
  V_USER(88) = V(115)
  V_USER(89) = V(158)
  V_USER(90) = V(84)
  V_USER(91) = V(96)
  V_USER(92) = V(106)
  V_USER(93) = V(191)
  V_USER(94) = V(128)
  V_USER(95) = V(127)
  V_USER(96) = V(124)
  V_USER(97) = V(200)
  V_USER(98) = V(110)
  V_USER(99) = V(101)
  V_USER(100) = V(186)
  V_USER(101) = V(102)
  V_USER(102) = V(187)
  V_USER(103) = V(92)
  V_USER(104) = V(177)
  V_USER(105) = V(105)
  V_USER(106) = V(109)
  V_USER(107) = V(169)
  V_USER(108) = V(196)
  V_USER(109) = V(197)
  V_USER(110) = V(171)
  V_USER(111) = V(149)
  V_USER(112) = V(140)
  V_USER(113) = V(139)
  V_USER(114) = V(141)
  V_USER(115) = V(98)
  V_USER(116) = V(22)
  V_USER(118) = V(204)
  V_USER(119) = V(203)
  V_USER(120) = V(138)
  V_USER(121) = V(117)
  V_USER(122) = V(23)
  V_USER(123) = V(82)
  V_USER(124) = V(9)
  V_USER(125) = V(10)
  V_USER(126) = V(67)
  V_USER(127) = V(24)
  V_USER(128) = V(25)
  V_USER(129) = V(159)
  V_USER(130) = V(126)
  V_USER(131) = V(121)
  V_USER(132) = V(178)
  V_USER(133) = V(194)
  V_USER(134) = V(180)
  V_USER(135) = V(26)
  V_USER(136) = V(27)
  V_USER(137) = V(123)
  V_USER(138) = V(174)
  V_USER(139) = V(28)
  V_USER(140) = V(29)
  V_USER(141) = V(30)
  V_USER(142) = V(31)
  V_USER(143) = V(33)
  V_USER(144) = V(32)
  V_USER(145) = V(34)
  V_USER(146) = V(35)
  V_USER(147) = V(201)
  V_USER(148) = V(160)
  V_USER(149) = V(104)
  V_USER(150) = V(205)
  V_USER(151) = V(65)
  V_USER(152) = V(209)
  V_USER(153) = V(100)
  V_USER(154) = V(114)
  V_USER(155) = V(153)
  V_USER(156) = V(134)
  V_USER(157) = V(188)
  V_USER(158) = V(166)
  V_USER(159) = V(179)
  V_USER(160) = V(68)
  V_USER(161) = V(192)
  V_USER(162) = V(210)
  V_USER(163) = V(135)
  V_USER(164) = V(53)
  V_USER(165) = V(136)
  V_USER(166) = V(152)
  V_USER(167) = V(69)
  V_USER(168) = V(116)
  V_USER(169) = V(66)
  V_USER(170) = V(36)
  V_USER(171) = V(112)
  V_USER(172) = V(113)
  V_USER(173) = V(198)
  V_USER(174) = V(89)
  V_USER(175) = V(129)
  V_USER(176) = V(143)
  V_USER(177) = V(162)
  V_USER(178) = V(190)
  V_USER(179) = V(163)
  V_USER(180) = V(118)
  V_USER(181) = V(57)
  V_USER(182) = V(48)
  V_USER(183) = V(49)
  V_USER(184) = V(211)
  V_USER(185) = V(212)
  V_USER(186) = V(207)
  V_USER(187) = V(70)
  V_USER(189) = V(206)
  V_USER(190) = V(11)
  V_USER(191) = V(213)
  V_USER(192) = V(37)
  V_USER(193) = V(172)
  V_USER(194) = V(173)
  V_USER(195) = V(164)
  V_USER(196) = V(60)
  V_USER(197) = V(175)
  V_USER(198) = V(91)
  V_USER(199) = V(142)
  V_USER(200) = V(86)
  V_USER(201) = V(55)
  V_USER(202) = V(150)
  V_USER(203) = V(154)
  V_USER(204) = V(184)
  V_USER(205) = V(87)
  V_USER(206) = V(83)
  V_USER(207) = V(148)
  V_USER(208) = V(168)
  V_USER(209) = V(176)
  V_USER(210) = V(71)
  V_USER(211) = V(72)
  V_USER(212) = V(73)
  V_USER(213) = V(181)

END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! GetMass - compute total mass of selected atoms
!   Arguments :
!      CL        - Concentration of all species (local)
!      Mass      - value of mass balance
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE GetMass ( CL, Mass )

! CL - Concentration of all species (local)
  REAL(kind=dp) :: CL(NSPEC)
! Mass - value of mass balance
  REAL(kind=dp) :: Mass(1)


END SUBROUTINE GetMass

! End of GetMass function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! Get_OHreactivity - returns the OH reactivity
! The OH reactivity is defined as the inverse of its lifetime.
! This routine was auto-generated using script OHreact_parser.py.
! Generated on 2021-02-11
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Get_OHreactivity ( CC, RR, OHreact )

! CC - Concentrations of species (local)
  REAL(kind=dp) :: CC(NSPEC)
! RR - reaction rates (local)
  REAL(kind=dp) :: RR(NREACT)
! OHreact - OH reactivity [s-1]
  REAL(kind=dp) :: OHreact

  OHreact = RR(2)*CC(206) + 2*RR(6) + 2*RR(7) + RR(8)*CC(208) + RR(9)*CC(88) &
          + RR(12)*CC(215) + RR(13)*CC(202) + RR(14)*CC(214) + RR(20)*CC(69) + RR(21)*CC(69) &
          + RR(22)*CC(146) + RR(23)*CC(146) + RR(24)*CC(189) + RR(25)*CC(212) + RR(26)*CC(170) &
          + RR(27)*CC(211) + RR(28)*CC(80) + RR(31)*CC(81) + RR(34)*CC(207) + RR(37)*CC(99) &
          + RR(38)*CC(135) + RR(41)*CC(182) + RR(46)*CC(62) + RR(50)*CC(54) + RR(51)*CC(54) &
          + RR(55)*CC(64) + RR(65)*CC(168) + RR(66)*CC(111) + RR(67)*CC(181) + RR(72)*CC(130) &
          + RR(81)*CC(179) + RR(91)*CC(77) + RR(92)*CC(120) + RR(102)*CC(184) + RR(104)*CC(157) &
          + RR(105)*CC(157) + RR(107)*CC(185) + RR(108)*CC(192) + RR(111)*CC(195) + RR(112)*CC(195) &
          + RR(119)*CC(87) + RR(120)*CC(85) + RR(121)*CC(72) + RR(122)*CC(73) + RR(123)*CC(71) &
          + RR(124)*CC(74) + RR(125)*CC(86) + RR(126)*CC(33) + RR(127)*CC(65) + RR(152)*CC(76) &
          + RR(153)*CC(76) + RR(155)*CC(95) + RR(156)*CC(165) + RR(157)*CC(154) + RR(171)*CC(52) &
          + RR(172)*CC(56) + RR(173)*CC(75) + RR(181)*CC(112) + RR(182)*CC(113) + RR(192)*CC(123) &
          + RR(200)*CC(91) + RR(214)*CC(136) + RR(215)*CC(152) + RR(221)*CC(103) + RR(222)*CC(68) &
          + RR(223)*CC(78) + RR(224)*CC(67) + RR(225)*CC(70) + RR(227)*CC(159) + RR(228)*CC(159) &
          + RR(229)*CC(159) + RR(230)*CC(159) + RR(257)*CC(144) + RR(258)*CC(145) + RR(259)*CC(94) &
          + RR(260)*CC(97) + RR(261)*CC(147) + RR(262)*CC(133) + RR(263)*CC(84) + RR(264)*CC(119) &
          + RR(265)*CC(119) + RR(266)*CC(122) + RR(267)*CC(122) + RR(268)*CC(119) + RR(269)*CC(122) &
          + RR(270)*CC(131) + RR(271)*CC(125) + RR(284)*CC(92) + RR(285)*CC(101) + RR(286)*CC(101) &
          + RR(287)*CC(102) + RR(288)*CC(102) + RR(307)*CC(105) + RR(308)*CC(105) + RR(309)*CC(109) &
          + RR(310)*CC(109) + RR(311)*CC(177) + RR(312)*CC(177) + RR(313)*CC(169) + RR(314)*CC(169) &
          + RR(315)*CC(177) + RR(316)*CC(169) + RR(354)*CC(138) + RR(355)*CC(117) + RR(356)*CC(138) &
          + RR(357)*CC(117) + RR(358)*CC(117) + RR(359)*CC(138) + RR(360)*CC(117) + RR(361)*CC(117) &
          + RR(370)*CC(193) + RR(371)*CC(193) + RR(374)*CC(200) + RR(377)*CC(198) + RR(379)*CC(201) &
          + RR(380)*CC(201) + RR(383)*CC(190) + RR(384)*CC(162) + RR(385)*CC(188) + RR(386)*CC(153) &
          + RR(387)*CC(134) + RR(394)*CC(114) + RR(395)*CC(118) + RR(396)*CC(89) + RR(397)*CC(143) &
          + RR(398)*CC(129) + RR(399)*CC(100) + RR(405)*CC(104) + RR(417)*CC(116) + RR(418)*CC(79) &
          + RR(419)*CC(158) + RR(420)*CC(96) + RR(421)*CC(106) + RR(422)*CC(124) + RR(423)*CC(178) &
          + RR(424)*CC(194) + RR(426)*CC(83) + RR(427)*CC(63) + RR(429)*CC(132) + RR(430)*CC(132)

END SUBROUTINE Get_OHreactivity
! End of Get_OHreactivity subroutine
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

END MODULE gckpp_Util
